version: '3'

services:
  postgres:
    image: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=animes
    ports:
      - 5432:5432
    networks:
       - network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'seila@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'animes'
    ports:
      - '16543:80'
    depends_on:
      - postgres
    networks:
      - network

networks:
  network:
    driver: bridge
